deploy/create_project.py
deploy/utils/forseti.py

Fix bug in get_iam_policy_cleanup. Also remove clean-up lines for Forseti service account.

Fix bug in get_iam_policy_cleanup. Also remove clean-up lines for Forseti service account.

---

deploy/create_project.py

Add temporary flag to enable/disable the CFT part.

Add temporary flag to enable/disable the CFT part.

---

deploy/BUILD
deploy/cft/cft.go
deploy/create_project.py

plug in cft binary to create_project

plug in cft binary to create_project

---

deploy/project_config.yaml.schema

update schema to include new style resources

update schema to include new style resources

---

deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/gcs_bucket_test.go

remove automated prefix addition for buckets

remove automated prefix addition for buckets

---

deploy/cft/BUILD
deploy/cft/binding.go
deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/pubsub.go
deploy/cft/pubsub_test.go
deploy/cft/templates/pubsub.py
deploy/cft/templates/pubsub.py.schema
deploy/project_config.yaml.schema

add support for pubsub

---

deploy/create_project.py
deploy/create_project_test.py
deploy/project_config.yaml.schema
deploy/samples/project_with_remote_audit_logs.yaml
deploy/samples/spanned_configs/partial_projects.yaml
deploy/templates/data_project.py
deploy/templates/data_project.py.schema
deploy/templates/data_project_test.py

Add a name entry in data_bucket so that users can specify the bucket name directly.

Add a name entry in data_bucket so that users can specify the bucket name directly.

---

deploy/rule_generator/project_config.py

Add a name entry in data_bucket (rule_generator).

Add a name entry in data_bucket (rule_generator).

---

deploy/rule_generator/scanners/iam_scanner_rules_test.py

Update iam scanner rule generator test case for 'name' in data buckets.

Update iam scanner rule generator test case for 'name' in data buckets.

---

deploy/utils/runner.py

Update fake_run() to enable dry_run mode.

Update fake_run() to enable dry_run mode.

---

deploy/utils/runner.py

Remove unnecessary fake command from the function fake_run()

Remove unnecessary fake command from the function fake_run()

---

deploy/project_config.yaml.schema

temporarily remove check for oneOf

temporarily remove check for oneOf

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/gcs_bucket_test.go
deploy/cft/templates/gcs_bucket.py.schema

set gcs logging bucket

---

deploy/cft/pubsub.go
deploy/cft/resourcepair.go

support partial implementation of slice items

support partial implementation of slice items

---

WORKSPACE
deploy/cft/bigquery_dataset.go
deploy/cft/cft.go
deploy/cmd/rule_generator/BUILD
deploy/cmd/rule_generator/rule_generator.go
deploy/rulegen/BUILD
deploy/rulegen/bigquery.go
deploy/rulegen/bigquery_test.go
deploy/rulegen/resource.go
deploy/rulegen/rulegen.go
deploy/rulegen/rulegen_test.go

first version of new rule generator

first version of new rule generator

---

deploy/cft/cft.go
deploy/rulegen/bigquery.go
deploy/rulegen/log_sink.go
deploy/rulegen/log_sink_test.go
deploy/rulegen/resource.go

port log sink scanner rules to new rule generator

port log sink scanner rules to new rule generator

---

deploy/rulegen/BUILD
deploy/rulegen/audit_logging.go
deploy/rulegen/audit_logging_test.go
deploy/rulegen/bucket.go
deploy/rulegen/bucket_test.go
deploy/rulegen/cloud_sql.go
deploy/rulegen/cloud_sql_test.go
deploy/rulegen/lien.go
deploy/rulegen/lien_test.go
deploy/rulegen/resource.go

port global only scanner rules to new rule generator

port global only scanner rules to new rule generator

---

deploy/cft/cft.go
deploy/cft/gke_workload.go
deploy/cft/gke_workload_test.go

Enable GKE workloads get the location information of GKE clusters.

Enable GKE workloads get the location information of GKE clusters.

---

deploy/rulegen/bigquery.go

fix flaky tests due to unstable map order

fix flaky tests due to unstable map order

---

deploy/cft/bigquery_dataset.go
deploy/cft/bigquery_dataset_test.go
deploy/cft/cft.go

don't allow special group or view

don't allow special group or view

---

deploy/cft/bigquery_dataset_test.go
deploy/cft/deployment_test.go
deploy/cft/gcs_bucket_test.go

tests: fix accidental closure on parent testing.T.

tests: fix accidental closure on parent testing.T.

---

deploy/cft/cft.go
deploy/cmd/rule_generator/rule_generator.go
deploy/rulegen/resource.go
deploy/rulegen/rulegen.go
deploy/rulegen/rulegen_test.go

generators

---

deploy/cft/templates/gcs_bucket.py
deploy/cft/templates/gcs_bucket.py.schema

sync bucket template to head

---

deploy/rulegen/bigquery.go
deploy/rulegen/bigquery_test.go
deploy/rulegen/enabled_apis.go
deploy/rulegen/location.go
deploy/rulegen/location_test.go
deploy/rulegen/log_sink.go
deploy/rulegen/log_sink_test.go
deploy/rulegen/resource.go
deploy/rulegen/resource_test.go

use all projects helper in all scanner rule generators

use all projects helper in all scanner rule generators

---

deploy/create_project.py
deploy/project_config.yaml.schema

custom boot image

---

deploy/cft/gce_instance.go
deploy/cft/gce_instance_test.go

set custom boot image on CFT resource if defined

set custom boot image on CFT resource if defined

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/iam.go
deploy/cft/iam_test.go
deploy/cft/templates/iam_member/iam_member.py
deploy/cft/templates/iam_member/iam_member.py.schema
deploy/project_config.yaml.schema
deploy/rulegen/bigquery.go
deploy/rulegen/iam.go
deploy/rulegen/iam_test.go
deploy/rulegen/location.go
deploy/rulegen/resource.go

add support for CFT iam policies

add support for CFT iam policies

---

deploy/cft/templates/README.md

update cft url to new repo

---

deploy/BUILD
deploy/create_project.py
deploy/project_config.yaml.schema
deploy/rule_generator/BUILD
deploy/rule_generator/project_config.py
deploy/rule_generator/project_config_test.py
deploy/rule_generator/rule_generator.py
deploy/rule_generator/scanners/scanner_test_utils.py
deploy/utils/BUILD
deploy/utils/field_generation.py
deploy/utils/field_generation_test.py

Move generated fields out of projects.

Move generated fields out of projects.

---

deploy/cft/cft.go
deploy/cft/deployment.go
deploy/cft/deployment_test.go

explicitly pass in deployment name

explicitly pass in deployment name

---

deploy/cft/bigquery_dataset.go
deploy/cft/cft.go
deploy/cft/gcs_bucket.go
deploy/rulegen/bigquery.go
deploy/rulegen/iam.go
deploy/rulegen/iam_test.go
deploy/rulegen/location.go
deploy/rulegen/log_sink.go
deploy/rulegen/resource.go
deploy/rulegen/resource_test.go
deploy/rulegen/rulegen.go

rule generator fixes and improvements

rule generator fixes and improvements

---

deploy/cft/BUILD
deploy/cft/logsink.go
deploy/cft/logsink_test.go

add log sink resource

---

deploy/cft/cft.go
deploy/create_project.py
deploy/project_config.yaml.schema
deploy/rulegen/resourceutil.go

add support for project level billing and folder id

add support for project level billing and folder id

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/generated_fields.go
deploy/cft/generated_fields_test.go
deploy/rulegen/bigquery.go
deploy/rulegen/iam.go
deploy/rulegen/location.go
deploy/rulegen/resource.go
deploy/rulegen/rulegen.go
deploy/rulegen/rulegen_test.go

Transfer CFT resources's generated_fields to new format.

Transfer CFT resources's generated_fields to new format.

---

deploy/utils/field_generation.py
deploy/utils/field_generation_test.py

Add support for writing generated_fields back to yaml files.

Add support for writing generated_fields back to yaml files.

---

deploy/cft/cft.go
deploy/cft/generated_fields.go
deploy/cft/generated_fields_test.go
deploy/rulegen/bigquery.go
deploy/rulegen/iam.go
deploy/rulegen/location.go
deploy/rulegen/resource.go
deploy/rulegen/rulegen.go

set generated fields in project struct and set in config init, simplify tests

set generated fields in project struct and set in config init, simplify tests

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/gcs_bucket_test.go
deploy/cmd/cft/cft.go
deploy/project_config.yaml.schema
deploy/rulegen/audit_logging_test.go
deploy/rulegen/bigquery.go
deploy/rulegen/iam.go
deploy/rulegen/location.go
deploy/rulegen/log_sink.go
deploy/rulegen/resource.go
deploy/rulegen/rulegen_test.go

port audit log resources to CFT

port audit log resources to CFT

---

deploy/deploymentmanager/BUILD

fix import path

---

deploy/create_project.py
deploy/integration_test/integration_test.yaml
deploy/integration_test/project1.yaml
deploy/utils/field_generation.py

Use rewrite_generated_fields_back in the code.

Use rewrite_generated_fields_back in the code.

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/metric.go
deploy/templates/BUILD
deploy/templates/audit_log_config.py

Port over default resources in templates/data_project.py to CFT

Port over default resources in templates/data_project.py to CFT

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gke_cluster.go
deploy/cft/gke_cluster_test.go
deploy/cft/gke_workload.go
deploy/cft/gke_workload_test.go
deploy/rulegen/bigquery.go
deploy/rulegen/bigquery_test.go
deploy/rulegen/iam.go
deploy/rulegen/iam_test.go
deploy/rulegen/location.go
deploy/rulegen/location_test.go
deploy/rulegen/resource.go
deploy/rulegen/resource_test.go

change resource definition syntax to simplify code

change resource definition syntax to simplify code

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/gcs_bucket_test.go
deploy/cft/logsink.go
deploy/cft/logsink_test.go
deploy/cmd/cft/cft.go
deploy/deploymentmanager/deploymentmanager.go
deploy/deploymentmanager/deploymentmanager_test.go
deploy/rulegen/log_sink.go
deploy/rulegen/log_sink_test.go

do audit deployment as part of CFT

do audit deployment as part of CFT

---

deploy/cft/cft.go
deploy/cft/gke_workload.go
deploy/cft/gke_workload_test.go

cleanup gke workload

---

deploy/BUILD
deploy/create_project.py

break up create_project.py with flag guards to stop deployment of steps moved to CFT

break up create_project.py with flag guards to stop deployment of steps moved to CFT

---

deploy/project_config.yaml.schema

update cft modules schewma

---

deploy/README.md

update outdated notice on deployment updates

update outdated notice on deployment updates

---

deploy/cft/templates/forseti/client.py
deploy/cft/templates/forseti/client.py.schema
deploy/cft/templates/forseti/forseti.py
deploy/cft/templates/forseti/forseti.py.schema
deploy/cft/templates/forseti/server.py
deploy/cft/templates/forseti/server.py.schema

add forseti CFT templates

---

deploy/README.md
deploy/cft/BUILD
deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/gcs_bucket_test.go
deploy/cft/gke_workload.go
deploy/cmd/cft/cft.go
deploy/cmd/rule_generator/rule_generator.go
deploy/create_project.py
deploy/rulegen/iam.go
deploy/rulegen/iam_test.go
deploy/rulegen/rulegen.go
deploy/rulegen/rulegen_test.go

port over remaining core functionality from create_project.py to CFT

port over remaining core functionality from create_project.py to CFT

---

deploy/project_config.yaml.schema

improve cft resource docs

---

deploy/samples/minimal.yaml

add minimal config that we can point to for newcomers wanting to test DPT

add minimal config that we can point to for newcomers wanting to test DPT

---

deploy/utils/utils.py
deploy/utils/utils_test.py

Add a tool to split chc_monitor_projects.

Add a tool to split chc_monitor_projects.

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/gcs_bucket.go
deploy/cft/metric.go
deploy/deploymentmanager/deploymentmanager.go

simplify logic to get dependent resources

simplify logic to get dependent resources

---

WORKSPACE
deploy/BUILD
deploy/README.md
deploy/create_project_test.py
deploy/requirements.txt
deploy/rule_generator/BUILD
deploy/rule_generator/rule_generator.py
deploy/rule_generator/scanners/BUILD
deploy/templates/BUILD
deploy/utils/BUILD
deploy/utils/forseti.py
deploy/utils/forseti_test.py

Support python3 only

---

deploy/cft/cft.go
deploy/cft/cft_test.go
deploy/cft/templates/firewall/firewall.py
deploy/cft/templates/firewall/firewall.py.schema

rename firewall to gce_firewall for consistency

rename firewall to gce_firewall for consistency

---

deploy/cft/templates/network/network.py
deploy/cft/templates/network/network.py.schema
deploy/cft/templates/network/subnetwork.py
deploy/cft/templates/network/subnetwork.py.schema

Add network and subnetwork templates.

Add network and subnetwork templates.

---

deploy/BUILD
deploy/cmd/apply/BUILD
deploy/cmd/apply/apply.go
deploy/create_project.py

rename cft bin to apply

---

deploy/project_config.yaml.schema

Correct schema errors

---

deploy/README.md

rename header for consistency with new "DPT" name

rename header for consistency with new "DPT" name

---

deploy/README.md
deploy/project_config.yaml.schema

add resources table to readme

---

deploy/utils/forseti.py

switch forseti installer to py3

switch forseti installer to py3

---

deploy/project_config.yaml.schema

firewalls -> gce_firewalls in schema

firewalls -> gce_firewalls in schema

---

deploy/README.md
deploy/create_project.py
deploy/create_project_test.py

deprecate output cleanup file

---

deploy/README.md

add debug section, mention permission denied issue

add debug section, mention permission denied issue

---

deploy/apply/apply.go
deploy/apply/apply_test.go

return error when failing to remove owner user, fix test to return valid JSON

return error when failing to remove owner user, fix test to return valid JSON

---

deploy/README.md

document dependencies

---

WORKSPACE
deploy/apply/BUILD
deploy/config/BUILD
deploy/project_config.yaml.schema
deploy/rulegen/BUILD
deploy/testconf/BUILD
deploy/testconf/testconf.go

validate config in tests

---

deploy/config/templates/gcs_bucket/gcs_bucket.py
deploy/config/templates/gcs_bucket/gcs_bucket.py.schema

sync gcs bucket template with https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/87

sync gcs bucket template with https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/87

---

deploy/samples/datathon_team_project.yaml
deploy/samples/minimal.yaml
deploy/samples/project_with_local_audit_logs.yaml
deploy/samples/project_with_remote_audit_logs.yaml
deploy/samples/spanned_configs/partial_audit.yaml
deploy/samples/spanned_configs/partial_other_projects.yaml
deploy/samples/spanned_configs/partial_projects.yaml

migrate samples to CFT

---

deploy/samples/datathon_team_project.yaml

fix instance sample

---

deploy/README.md

update readme for CFT

---

deploy/rulegen/bigquery.go
deploy/rulegen/iam.go

fix long rule names

---

deploy/create_project.py
deploy/create_project.sh
deploy/utils/utils.py

Do not call the Golang part in dry_run mode.

Do not call the Golang part in dry_run mode.

---

deploy/samples/project_with_local_audit_logs.yaml
deploy/samples/project_with_remote_audit_logs.yaml

Update Datathon organizer setup scrips to be compatible with changes to deployment.

Update Datathon organizer setup scrips to be compatible with changes to deployment.

---

deploy/config/BUILD
deploy/config/service_account.go
deploy/config/service_account_test.go

Add DM support for "iam.v1.serviceAccount" to deploy service accounts.

Add DM support for "iam.v1.serviceAccount" to deploy service accounts.

---

WORKSPACE
deploy/config/BUILD
deploy/config/read_config.go
deploy/config/read_config_test.go

Implement normalize path in the Golang part of the DPT.

Implement normalize path in the Golang part of the DPT.

---

deploy/config/templates/firewall/firewall.py
deploy/config/templates/firewall/firewall.py.schema

Update the firewall CFT template.

Update the firewall CFT template.

---

WORKSPACE

Update io_bazel_rules_go so that bazel works.

Update io_bazel_rules_go so that bazel works.

---

deploy/config/BUILD
deploy/config/config.go
deploy/config/read_config.go
deploy/config/read_config_test.go
deploy/testconf/test_multiple_yaml/conf.yaml
deploy/testconf/test_multiple_yaml/expected.yaml
deploy/testconf/test_multiple_yaml/project1.yaml
deploy/testconf/test_multiple_yaml/project2.yaml

Support "imports" in the Golang part.

Support "imports" in the Golang part.

---

deploy/config/templates/chc_resource/chc_res_type_provider.yaml

Add CHC resource Deployment Manager Type Provider.

Add CHC resource Deployment Manager Type Provider.

---

deploy/config/config.go
deploy/config/metric_test.go
deploy/project_config.yaml.schema
deploy/testconf/testconf.go

Support specify violation_exceptions on log based metrics.

Support specify violation_exceptions on log based metrics.

---

deploy/apply/apply.go
deploy/apply/apply_test.go

Do not update remote audit log project when updating a data project.

Do not update remote audit log project when updating a data project.

---

deploy/create_project.py

use CFT configs by default

---

fhir/immunizations_demo/docs/README.md

Update import and export commands to reflect v1beta1 requests.

Update import and export commands to reflect v1beta1 requests.

---

fhir/immunizations_demo/scripts/assemble_training_data.py
fhir/lung-cancer/scripts/assemble_training_data.py

Upgrade deprecated usage of TFRecordWriter.
Closes #134

Upgrade deprecated usage of TFRecordWriter.

---

deploy/create_project.py

Enable healthcare API automatically when there is Healthcare resources in config file.

Enable healthcare API automatically when there is Healthcare resources in config file.

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/config/templates/BUILD
deploy/deploymentmanager/deploymentmanager.go

Deploy CHC type provider in DPT

Deploy CHC type provider in DPT

---

deploy/config/BUILD
deploy/config/templates/chc_resource/BUILD
deploy/config/templates/chc_resource/chc_dataset.py
deploy/config/templates/chc_resource/chc_dataset.py.schema
deploy/config/templates/chc_resource/chc_dataset_test.py
deploy/config/templates/chc_resource/examples/chc_dataset.yaml

Add a DM template for CHC Dataset.

Add a DM template for CHC Dataset.

---

deploy/README.md
deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/config/BUILD
deploy/config/chc_dataset.go
deploy/config/chc_dataset_test.go
deploy/config/config.go
deploy/create_project.py
deploy/project_config.yaml.schema

DPT supports CHC resources.

---

deploy/apply/apply.go

set audit gcs bucket iff it exists

set audit gcs bucket iff it exists

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/config/bigquery_dataset.go
deploy/config/config.go
deploy/rulegen/bigquery.go

always deploy latest log sink writer
It seems like the log sink writer can change (most likely when being moved between deployments).

always deploy latest log sink writer

---

deploy/create_project.py

Do not create project deletion lien when create_deletion_lien is false.

Do not create project deletion lien when create_deletion_lien is false.

---

deploy/create_project.py

always get latest log sink service account in generated fields

always get latest log sink service account in generated fields

---

deploy/apply/apply.go
deploy/config/config.go

fix SA permission being added on undeployed project

fix SA permission being added on undeployed project

---

deploy/apply/apply.go

write cmd stdout to OS stdout

---

deploy/apply/apply.go

don't set stdout for output

---

deploy/samples/sandbox_project_demo.yaml

Add a sandbox demo YAML

---

deploy/config/load.go
deploy/project_config.yaml.schema
deploy/testconf/test_multiple_yaml/conf.yaml
deploy/utils/utils.py

Change the items of "imports" from strings to objects.

Change the items of "imports" from strings to objects.

---

deploy/config/templates/vpn/vpn.py
deploy/config/templates/vpn/vpn.py.schema

Add CFT VPN DM template

---

deploy/BUILD
deploy/README.md
deploy/apply/BUILD
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/cmd/apply_forseti/BUILD
deploy/cmd/apply_forseti/apply_forseti.go
deploy/config/BUILD
deploy/config/config.go
deploy/config/forseti.go
deploy/config/forseti_test.go
deploy/config/load.go
deploy/config/terraform.go
deploy/config/terraform_test.go
deploy/create_project.py
deploy/project_config.yaml.schema
deploy/rulegen/resourceutil.go
deploy/testconf/testconf.go

migrate forseti installation logic to Terraform

migrate forseti installation logic to Terraform

---

deploy/samples/project_with_local_audit_logs.yaml
deploy/samples/project_with_remote_audit_logs.yaml
deploy/samples/spanned_configs/partial_audit.yaml

update forseti samples to be valid for TF

update forseti samples to be valid for TF

---

deploy/apply/forseti.go

update TODO location

---

deploy/config/gcs_bucket.go

change bucket lifecycle implementation to use custom marshallers over pairs

change bucket lifecycle implementation to use custom marshallers over pairs

---

deploy/config/load.go
deploy/config/load_test.go
deploy/samples/template/input.yaml
deploy/samples/template/overall.tmpl.yaml
deploy/samples/template/project.tmpl.yaml

add support for templates

---

deploy/config/config.go

remove outdated comment

---

deploy/BUILD
deploy/cmd/load_config/BUILD
deploy/cmd/load_config/load_config.go
deploy/config/load.go
deploy/create_project.py
deploy/project_config.yaml.schema
deploy/utils/runner.py

use go config loader in python code

use go config loader in python code

---

deploy/apply/apply_test.go
deploy/config/config.go
deploy/config/default_resource.go
deploy/config/default_resource_test.go
deploy/project_config.yaml.schema
deploy/samples/datathon_team_project.yaml

allow default resource to handle name being set outside properties block

allow default resource to handle name being set outside properties block

---

deploy/config/load.go

use yaml.marshal to preserve yaml formatting

use yaml.marshal to preserve yaml formatting

---

deploy/cmd/load_config/load_config.go
deploy/config/BUILD
deploy/config/load.go
deploy/config/load_test.go
deploy/create_project.py
deploy/testconf/BUILD
deploy/testconf/testconf.go

Move config validation for go in load_config.go.

Move config validation for go in load_config.go.

---

deploy/config/load.go
deploy/config/load_test.go
deploy/testconf/testconf.go

minor improvements to config validation

minor improvements to config validation

---

deploy/README.md
deploy/create_project.py
deploy/create_project_test.py
deploy/utils/field_generation.py

make output_yaml_path optional

make output_yaml_path optional

---

deploy/config/BUILD

add missing project config schema data dependency

add missing project config schema data dependency

---

deploy/samples/BUILD
deploy/starlark/BUILD
deploy/starlark/config_test.bzl
deploy/testconf/BUILD

Create a config_test rule to validate configs.

Create a config_test rule to validate configs.

---

deploy/samples/BUILD

Rename tests to be more consistent with others.

Rename tests to be more consistent with others.

---

deploy/create_project.py

add more checks to enable necessary APIs

add more checks to enable necessary APIs

---

deploy/config/gke_cluster.go
deploy/config/templates/gke/gke.py
deploy/config/templates/gke/gke.py.schema

Update GKE template from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev"

Update GKE template from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev"

---

deploy/config/load.go
deploy/samples/template/overall.tmpl.yaml

set missingkey=error on templates

set missingkey=error on templates

---

deploy/config/templates/firewall/firewall.py
deploy/config/templates/firewall/firewall.py.schema

Update firewall CFT template from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev"

Update firewall CFT template from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev"

---

deploy/samples/BUILD
deploy/samples/template/BUILD
deploy/starlark/config_test.bzl

Support additional configs/templates in config_test.

Support additional configs/templates in config_test.

---

deploy/config/load_test.go

Add unit tests for config.Validate()

Add unit tests for config.Validate()

---

deploy/config/config.go

Always sort project before creating rules.

Always sort project before creating rules.

---

deploy/starlark/config_test.bzl

Enforce at least 1 file match if imports is specified.

Enforce at least 1 file match if imports is specified.

---

deploy/config/load.go

enforce at least 1 file found by pattern

enforce at least 1 file found by pattern

---

WORKSPACE
deploy/config/BUILD

Fix build/test of the oss version.

Fix build/test of the oss version.

---

deploy/config/templates/network_peering/network_peering.py
deploy/config/templates/network_peering/network_peering.py.schema

Add network_peering CFT template.

Add network_peering CFT template.

---

deploy/create_project.py

Fix issue with project re-creation even project exists.

Fix issue with project re-creation even project exists.

---

deploy/apply/apply.go
deploy/apply/gke.go
deploy/apply/gke_test.go
deploy/config/BUILD
deploy/config/binary_authorization.go
deploy/config/config.go
deploy/project_config.yaml.schema

Support binary authorization.

---

deploy/config/templates/ip_reservation/ip_address.py
deploy/config/templates/ip_reservation/ip_address.py.schema
deploy/config/templates/ip_reservation/ip_reservation.py
deploy/config/templates/ip_reservation/ip_reservation.py.schema

DPT supports static IP addresses deployment.

DPT supports static IP addresses deployment.

---

deploy/create_project.py

Update doc for generated fields path.

Update doc for generated fields path.

---

deploy/config/templates/cloud_router/cloud_router.py
deploy/config/templates/cloud_router/cloud_router.py.schema

Add CFT cloud router DM template from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev/dm/templates/cloud_router".

Add CFT cloud router DM template from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev/dm/templates/cloud_router".

---

deploy/project_config.yaml.schema

remove deprecated fields from schema

remove deprecated fields from schema

---

deploy/apply/apply_test.go
deploy/config/config.go
deploy/project_config.yaml.schema

DPT supports cloud router.

---

deploy/config/templates/route/route.py
deploy/config/templates/route/route.py.schema

Add CFT route DM template into DPT from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev/dm/templates/route".

Add CFT route DM template into DPT from "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev/dm/templates/route".

---

deploy/BUILD
deploy/cmd/load_config/load_config.go
deploy/config/BUILD
deploy/config/load.go
deploy/config/load_test.go
deploy/create_project.py
deploy/generated_fields.yaml.schema
deploy/starlark/config_test.bzl
deploy/testconf/testconf.go

Validate separate generated fields file as part of load_config.go.

Validate separate generated fields file as part of load_config.go.

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/apply/options.go
deploy/cmd/apply/apply.go

add options for apply calls

---

deploy/README.md

Update doc regarding output yaml and generated fields.

Update doc regarding output yaml and generated fields.

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/config/bigquery_dataset.go
deploy/config/bigquery_dataset_test.go
deploy/config/chc_dataset.go
deploy/config/chc_dataset_test.go
deploy/config/config.go
deploy/config/default_resource.go
deploy/config/default_resource_test.go
deploy/config/gce_instance.go
deploy/config/gce_instance_test.go
deploy/config/gcs_bucket.go
deploy/config/gcs_bucket_test.go
deploy/config/gke_cluster.go
deploy/config/gke_cluster_test.go
deploy/config/iam.go
deploy/config/iam_test.go
deploy/config/logsink.go
deploy/config/logsink_test.go
deploy/config/metric.go
deploy/config/metric_test.go
deploy/config/pubsub.go
deploy/config/pubsub_test.go
deploy/config/service_account.go
deploy/config/service_account_test.go

set data resource related fields in project func, remove dep on project in resource inits

set data resource related fields in project func, remove dep on project in resource inits

---

deploy/README.md

update docs to reference bazel 0.27 and terraform 0.12

update docs to reference bazel 0.27 and terraform 0.12

---

deploy/cmd/load_config/load_config.go

Minor doc update.

---

deploy/BUILD
deploy/cmd/apply_resources/BUILD
deploy/cmd/apply_resources/apply_resources.go

Rename apply to apply_resources.

Rename apply to apply_resources.

---

deploy/cmd/apply/BUILD
deploy/cmd/apply/apply.go

Add skeleton for go-based DPT main script.

Add skeleton for go-based DPT main script.

---

deploy/create_project.py
deploy/create_project_test.py

Minor cleanup of unused code.

---

deploy/collector/BUILD
deploy/collector/README.md
deploy/collector/app.yaml
deploy/collector/collector.go
deploy/collector/cron.yaml
deploy/collector/processors/BUILD
deploy/collector/processors/audit_api_client.go
deploy/collector/processors/audit_api_client_test.go
deploy/collector/processors/gcs_client.go
deploy/collector/processors/processor.go

skelton cl for audit data collector. Only implemented processes for AuditConfig with fake APIs.

skelton cl for audit data collector. Only implemented processes for AuditConfig with fake APIs.

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/apply/options.go
deploy/cmd/apply/BUILD
deploy/cmd/apply/apply.go
deploy/cmd/apply_forseti/apply_forseti.go
deploy/cmd/apply_resources/apply_resources.go

Add project applier interface and implementation.

Add project applier interface and implementation.

---

deploy/apply/apply.go
deploy/apply/forseti.go

Reuse addBinding function in apply.go.

Reuse addBinding function in apply.go.

---

WORKSPACE
deploy/apply/BUILD
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/terraform/apply.go
deploy/terraform/apply_test.go

stop cloning repo, fetch the repo through bazel

stop cloning repo, fetch the repo through bazel

---

deploy/apply/apply.go
deploy/apply/forseti.go
deploy/cmd/apply/apply.go

Add logic to get forseti service account and bucket.

Add logic to get forseti service account and bucket.

---

deploy/apply/BUILD
deploy/apply/apply.go
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/gcs_bucket.go
deploy/create_project.py
deploy/project_config.yaml.schema
deploy/terraform/apply.go
deploy/terraform/apply_test.go
deploy/terraform/config.go
deploy/testconf/testconf.go

add initial support for state bucket, imports and resource references
This is all flag guarded with --enable_terraform.

add initial support for state bucket, imports and resource references

---

deploy/apply/apply.go
deploy/apply/apply_test.go

Add create project logic

---

deploy/create_project.py

Fix terraform boolean flag in go binary call.

Fix terraform boolean flag in go binary call.

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/config/config.go

Add enable billing and APIs logic.

Add enable billing and APIs logic.

---

deploy/apply/apply.go
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/apply/apply.go
deploy/cmd/apply_forseti/apply_forseti.go
deploy/create_project.py
deploy/terraform/apply_test.go
deploy/terraform/config.go

add support for terraform block

add support for terraform block

---

deploy/apply/terraform.go
deploy/config/gcs_bucket.go
deploy/project_config.yaml.schema
deploy/testconf/testconf.go

remove properties block from terraform buckets

remove properties block from terraform buckets

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/config/config.go
deploy/config/gce_instance.go

Add create custom GCE image logic.

Add create custom GCE image logic.

---

deploy/apply/forseti.go
deploy/apply/terraform.go
deploy/config/BUILD
deploy/config/config.go
deploy/config/gcs_bucket.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/config.go
deploy/config/tfconfig/pair.go
deploy/config/tfconfig/storage_bucket.go
deploy/config/tfconfig/storage_bucket_test.go

create new tfconfig package to temporarily hold terraform configs

create new tfconfig package to temporarily hold terraform configs

---

deploy/create_project.py
deploy/create_project_test.py
deploy/requirements.txt
deploy/utils/field_generation_test.py
deploy/utils/utils.py

Remove dependency on ruamel.

---

deploy/README.md

document when log sink reports an error on initial deployment

document when log sink reports an error on initial deployment

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/config/config.go

Add create stackdriver account logic.

Add create stackdriver account logic.

---

deploy/apply/apply.go
deploy/cmd/apply/apply.go
deploy/config/config.go
deploy/config/generated_fields.go
deploy/config/generated_fields_test.go
deploy/config/load.go

Write generated fields to output file.

Write generated fields to output file.

---

deploy/apply/BUILD
deploy/apply/apply.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/BUILD
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/config.go
deploy/config/tfconfig/storage_bucket.go
deploy/project_config.yaml.schema

add support for creating resources deployment, create storage buckets

add support for creating resources deployment, create storage buckets

---

deploy/apply/apply.go
deploy/runner/runner.go

Add logic to create Stackdriver channel.

Add logic to create Stackdriver channel.

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/tfconfig/pair.go
deploy/config/tfconfig/storage_bucket.go
deploy/project_config.yaml.schema
deploy/terraform/config.go

add support for bucket iam

---

deploy/apply/apply.go
deploy/config/config.go
deploy/runner/runner.go

Add create alerts logic.

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/bigquery_dataset.go
deploy/project_config.yaml.schema

add support for google_bigquery_dataset

add support for google_bigquery_dataset

---

deploy/apply/forseti.go
deploy/cmd/apply/apply.go

Skip Forseti config deployment if already deployed.

Skip Forseti config deployment if already deployed.

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/storage_bucket.go

fix for_each to be a map

---

deploy/cmd/apply/BUILD

add missing bazel dep

---

deploy/cmd/apply/apply.go

Only run rule generator if forseti is enabled.

Only run rule generator if forseti is enabled.

---

deploy/create_project.py

Fix creating alerts for GCS data bucket resources.

Fix creating alerts for GCS data bucket resources.

---

deploy/config/config.go
deploy/config/metric_test.go

use helper for getting audit projects in main init

use helper for getting audit projects in main init

---

deploy/create_project.py

Minor doc fix.

---

deploy/apply/apply_test.go
deploy/project_config.yaml.schema

Disable expected_users field in gcs_buckets.

Disable expected_users field in gcs_buckets.

---

deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/apply/apply.go
deploy/cmd/apply_forseti/apply_forseti.go
deploy/cmd/apply_resources/apply_resources.go
deploy/config/BUILD
deploy/config/config.go
deploy/config/load_test.go
deploy/config/terraform.go
deploy/create_project.py
deploy/project_config.yaml.schema
deploy/samples/project_with_local_audit_logs.yaml
deploy/samples/project_with_remote_audit_logs.yaml
deploy/samples/spanned_configs/partial_audit.yaml

deploy forseti remote state bucket even if terraform isn't enabled

deploy forseti remote state bucket even if terraform isn't enabled

---

deploy/apply/apply.go
deploy/cmd/apply/BUILD
deploy/cmd/apply/apply.go
deploy/cmd/apply/apply_test.go
deploy/cmd/apply/testdata/BUILD
deploy/cmd/apply/testdata/minimal_dryrun_commands.txt
deploy/runner/runner.go
deploy/starlark/BUILD

Add a simple dry run test using the minimal config.

Add a simple dry run test using the minimal config.

---

deploy/apply/apply.go
deploy/cmd/apply/apply.go
deploy/rulegen/rulegen.go

Write missing generated fields and some minor changes including
- Normalize local rulegen output path
- Check output_path and config_path should not be the same

Write missing generated fields and some minor changes including

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/load_config/load_config.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/bigquery_dataset.go
deploy/config/tfconfig/logging_sink.go
deploy/create_project.py
deploy/project_config.yaml.schema
deploy/terraform/apply.go
deploy/testconf/testconf.go

support deploying audit resources with terraform

support deploying audit resources with terraform

---

deploy/apply/apply.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/project.go

create project with terraform

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/iam.go
deploy/project_config.yaml.schema

add support for project iam member

add support for project iam member

---

deploy/config/generated_fields.go
deploy/generated_fields.yaml.schema

Remove unnecessary failed_step field in generated fields.

Remove unnecessary failed_step field in generated fields.

---

deploy/README.md

Update doc with new command line interface.

Update doc with new command line interface.

---

deploy/apply/forseti.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/iam.go
deploy/config/tfconfig/project.go
deploy/project_config.yaml.schema
deploy/terraform/config.go

add support for project service

add support for project service

---

deploy/cmd/load_config/BUILD
deploy/cmd/load_config/load_config.go
deploy/config/load.go
deploy/starlark/config_test.bzl

Enforce more checks in config_test.

Enforce more checks in config_test.

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/compute.go
deploy/project_config.yaml.schema

support compute instance and image

support compute instance and image

---

deploy/project_config.yaml.schema

make ttl_days not mandatory

---

deploy/cmd/apply/apply.go
deploy/cmd/rule_generator/rule_generator.go

Add a message in apply.go to guide users to run rule generator separately.

Add a message in apply.go to guide users to run rule generator separately.

---

deploy/README.md

clarify status of DPT

---

deploy/config/config.go
deploy/project_config.yaml.schema

make allowed_apis actually optional

make allowed_apis actually optional

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/terraform.go

rename terraform deployment to user deployment for clarity

rename terraform deployment to user deployment for clarity

---

deploy/apply/apply.go
deploy/runner/runner.go

Print stderr using log not os.stderr.

Print stderr using log not os.stderr.

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/project_config.yaml.schema

add project_ prefix to iam_members and services for consistency.

add project_ prefix to iam_members and services for consistency.

---

deploy/config/templates/bigquery/bigquery_dataset.py.schema

remove bigquery dataset location limitations

remove bigquery dataset location limitations

---

deploy/samples/BUILD
deploy/samples/spanned_configs/BUILD
deploy/samples/template/BUILD
deploy/starlark/config_test.bzl

Add `deps` attribute to config_test.

Add `deps` attribute to config_test.

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/config.go
deploy/config/tfconfig/logging.go
deploy/config/tfconfig/monitoring.go
deploy/project_config.yaml.schema
deploy/terraform/config.go

support deploying logging metrics and related and monitoring resources (notification channel, alert policy)

support deploying logging metrics and related and monitoring resources (notification channel, alert policy)

---

deploy/apply/terraform.go
deploy/config/tfconfig/bigquery.go
deploy/config/tfconfig/compute.go
deploy/config/tfconfig/logging.go
deploy/config/tfconfig/project.go
deploy/config/tfconfig/storage.go

change import id function signature to return (string, error)

change import id function signature to return (string, error)

---

deploy/config/load.go

Fix path normalization

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/monitoring.go

support importing existing monitoring channels and policies

support importing existing monitoring channels and policies

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/iam.go
deploy/project_config.yaml.schema

add support for service account

add support for service account

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/resource_manager.go
deploy/project_config.yaml.schema

support liens and project data access

support liens and project data access

---

deploy/apply/terraform_test.go
deploy/config/terraform.go
deploy/config/tfconfig/logging.go

fix metric to remove unit

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/terraform.go
deploy/terraform/config.go

fix alert policy to correctly reference monitoring channel, add support for providers and outputs in config

fix alert policy to correctly reference monitoring channel, add support for providers and outputs in config

---

deploy/apply/terraform_test.go
deploy/config/terraform.go

set owner on data hosting datasets

set owner on data hosting datasets

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go

rename deployment default to defaults for consistency

rename deployment default to defaults for consistency

---

deploy/apply/BUILD
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/iam.go

set default iam members in new pre requisite deployment, remove user owner

set default iam members in new pre requisite deployment, remove user owner

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/project.go

set default services

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/iam.go
deploy/project_config.yaml.schema

support iam custom role

---

deploy/apply/terraform_test.go
deploy/config/terraform.go

grant iam security reviewer permission and fix bigquery api to be bigquery-json

grant iam security reviewer permission and fix bigquery api to be bigquery-json

---

deploy/config/load.go

remove unncessary json.RawMessage in load

remove unncessary json.RawMessage in load

---

deploy/apply/apply.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/apply/testdata/project_with_remote_audit_logs_dryrun_commands.txt
deploy/config/config.go
deploy/config/terraform.go

simplify terraform code and tests

simplify terraform code and tests

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/iam.go

enable all audit logs in project

enable all audit logs in project

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/healthcare.go
deploy/project_config.yaml.schema

support healthcare resources

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go

rename user deployment to resources

rename user deployment to resources

---

deploy/apply/forseti.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/tfconfig/storage.go

merge project and state bucket deployments together

merge project and state bucket deployments together

---

deploy/apply/apply.go
deploy/apply/apply_test.go
deploy/apply/forseti.go
deploy/apply/options.go
deploy/apply/terraform.go
deploy/cmd/apply/apply.go
deploy/runner/runner.go

break project deployment into phases + apply phase to base projects

break project deployment into phases + apply phase to base projects

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/pubsub.go
deploy/config/tfconfig/resource_manager.go

fix imports for liens and pubsub

fix imports for liens and pubsub

---

deploy/apply/terraform.go
deploy/config/config.go
deploy/config/metric_test.go
deploy/project_config.yaml.schema
deploy/testconf/testconf.go

add support for devops project

add support for devops project

---

deploy/project_config.yaml.schema

deprecate `data_readwrite/readonly_groups`

deprecate `data_readwrite/readonly_groups`

---

deploy/apply/forseti.go
deploy/apply/options.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/apply/apply.go
deploy/cmd/apply/testdata/project_with_remote_audit_logs_dryrun_commands.txt
deploy/terraform/apply.go

make imports phase optional

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/compute.go
deploy/project_config.yaml.schema

add terraform support for compute firewalls

add terraform support for compute firewalls

---

deploy/apply/apply.go

don't remove user owner if specifically requested

don't remove user owner if specifically requested

---

deploy/config/load.go

Include bad attribute parent info in the error message.

Include bad attribute parent info in the error message.

---

deploy/starlark/config_test.bzl

add support for enabling terraform in config_test

add support for enabling terraform in config_test

---

deploy/samples/BUILD
deploy/samples/terraform.yaml

add sample terraform config

---

deploy/apply/terraform.go

fix terraform deployment when there is no base project to deploy

fix terraform deployment when there is no base project to deploy

---

deploy/config/terraform.go

enable pubsub api if pubsub topics are set

enable pubsub api if pubsub topics are set

---

deploy/apply/terraform_test.go
deploy/config/terraform.go
deploy/config/tfconfig/storage.go

set logging bucket for buckets

set logging bucket for buckets

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go

only import audit resources if --terraform_import_existing is passed

only import audit resources if --terraform_import_existing is passed

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/storage.go

port ttl_days field to terraform buckets

port ttl_days field to terraform buckets

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go

create audit deployment in project's own state bucket

create audit deployment in project's own state bucket

---

deploy/apply/apply.go
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/apply/terraform.go
deploy/cmd/apply/apply.go
deploy/cmd/apply/testdata/project_with_remote_audit_logs_dryrun_commands.txt
deploy/cmd/grant_forseti_access/grant_forseti_access.go

Use Terraform to grant forseti service account permissions.

Use Terraform to grant forseti service account permissions.

---

deploy/cmd/load_config/load_config.go

print generated fields as well in load_config

print generated fields as well in load_config

---

deploy/apply/terraform.go

parse terraform output for project number as JSON to avoid unexpected new lines

parse terraform output for project number as JSON to avoid unexpected new lines

---

deploy/apply/terraform.go

add comment explaining -json flag in terraform output command

add comment explaining -json flag in terraform output command

---

deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/config/config.go
deploy/project_config.yaml.schema
deploy/terraform/config.go

support adding arbitrary terraform provider resources

support adding arbitrary terraform provider resources

---

deploy/apply/apply.go
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/apply/options.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/apply/BUILD
deploy/cmd/apply/apply.go
deploy/cmd/apply/apply_test.go
deploy/cmd/grant_forseti_access/grant_forseti_access.go
deploy/terraform/apply.go

Enable output terraform configs to a user defined directory.

Enable output terraform configs to a user defined directory.

---

deploy/apply/terraform.go

clean up extra call to services deployment

clean up extra call to services deployment

---

deploy/README.md

add initial terraform documentation to describe phases and deployments

add initial terraform documentation to describe phases and deployments

---

deploy/cmd/apply/apply.go
deploy/project_config.yaml.schema

stop marking terraform related documentation as dev only

stop marking terraform related documentation as dev only

---

deploy/README.md

add missing resources in readme

add missing resources in readme

---

deploy/README.md

mark DM as legacy

---

deploy/README.md

more reordering and cleanup of README to isolate legacy from terraform

more reordering and cleanup of README to isolate legacy from terraform

---

deploy/project_config.yaml.schema

move terraform fields to the top of config schema

move terraform fields to the top of config schema

---

deploy/samples/generated_fields.yaml
deploy/samples/spanned_configs/base/base.yaml
deploy/samples/spanned_configs/generated_fields.yaml
deploy/samples/terraform.yaml

Add missing license headers.

---

deploy/samples/full/team1/config.yaml
deploy/samples/full/team2/project.tmpl.yaml
deploy/samples/resources/config.yaml

set notification channels in full example

set notification channels in full example

---

deploy/cmd/apply/apply.go

fix unhandled error

---

deploy/apply/apply.go
deploy/apply/forseti.go
deploy/cmd/apply/apply.go
deploy/cmd/apply/apply_test.go

Rename flag --terraform_configs_path to --terraform_configs_dir.

Rename flag --terraform_configs_path to --terraform_configs_dir.

---

deploy/WORKSPACE
deploy/cmd/apply/BUILD

Implement a container for the apply binary in DPT.

Implement a container for the apply binary in DPT.

---

deploy/apply/terraform_test.go

test condition gets parsed correctly

test condition gets parsed correctly

---

deploy/README.md

update readme to include more examples and why DPT should be used

update readme to include more examples and why DPT should be used

---

deploy/BUILD

internal change

---

deploy/samples/deployment_manager/BUILD
deploy/samples/deployment_manager/README.md
deploy/samples/deployment_manager/generated_fields.yaml
deploy/samples/deployment_manager/minimal.yaml
deploy/samples/deployment_manager/project_with_local_audit_logs.yaml
deploy/samples/deployment_manager/project_with_remote_audit_logs.yaml

bring back three main deployment manager samples

bring back three main deployment manager samples

---

deploy/apply/apply.go
deploy/apply/forseti.go
deploy/apply/forseti_test.go
deploy/apply/options.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/apply/apply.go
deploy/cmd/apply/apply_test.go
deploy/cmd/apply/testdata/commands.txt
deploy/cmd/grant_forseti_access/grant_forseti_access.go
deploy/terraform/apply.go

support passing extra flags to terraform apply call

support passing extra flags to terraform apply call

---

fhir/immunizations_demo/WORKSPACE

Update Go rules to fix build error in Immunizations demo

Update Go rules to fix build error in Immunizations demo

---

deploy/runner/runner.go

add resource-manager liens list in fake runner

add resource-manager liens list in fake runner

---

deploy/WORKSPACE
deploy/cmd/apply/BUILD
deploy/cmd/apply/apply.go

set correct shlex package

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/healthcare.go
deploy/samples/environments/project.tmpl.yaml

support import for hc dataset

---

deploy/config/load.go
deploy/config/load_test.go

support replace function in templates

support replace function in templates

---

deploy/presubmit.yaml

Add GCB job for presubmit.

---

deploy/project_config.yaml.schema

Fix an indent issue in schema which results in some resource config not being validated.

Fix an indent issue in schema which results in some resource config not being validated.

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/storage.go

set bucket_only_policy to true by default

set bucket_only_policy to true by default

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/iam.go

add imports for service accounts

add imports for service accounts

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/data_fusion.go

Set default values for data_fusion_instance.

Set default values for data_fusion_instance.

---

deploy/apply/terraform_test.go
deploy/config/tfconfig/data_fusion.go
deploy/samples/resources/config.yaml

Allow users to override defaults in data_fusion_instance.

Allow users to override defaults in data_fusion_instance.

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/cloudbuild.go
deploy/config/tfconfig/compute.go
deploy/project_config.yaml.schema
deploy/samples/resources/config.yaml

Support GCB trigger for GitHub.

Support GCB trigger for GitHub.

---

deploy/cmd/apply/apply.go

enable terraform by default

---

deploy/apply/terraform_test.go
deploy/config/terraform.go

Update bigquery API.
https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_project_service

Update bigquery API.

---

deploy/apply/forseti.go
deploy/apply/terraform.go
deploy/apply/terraform_test.go
deploy/cmd/apply/testdata/commands.txt
deploy/config/config.go

separate project and state bucket deployment to avoid https://github.com/terraform-providers/terraform-provider-google/issues/3429

separate project and state bucket deployment to avoid https://github.com/terraform-providers/terraform-provider-google/issues/3429

---

deploy/apply/terraform_test.go
deploy/cmd/apply/testdata/commands.txt
deploy/config/tfconfig/bigquery.go

fix dataset import
The format changed in https://github.com/GoogleCloudPlatform/magic-modules/commit/5204c70c01e623a2ea6d0b43570d6ec91c86d606#diff-e875b7b0281c5a98fe9570a5927029d1.

fix dataset import

---

deploy/apply/terraform_test.go
deploy/config/config.go
deploy/config/terraform.go
deploy/config/tfconfig/BUILD
deploy/config/tfconfig/spanner.go
deploy/project_config.yaml.schema

add support for spanner

---

deploy/config/terraform.go

grant owners group storage.admin

grant owners group storage.admin

---

imaging/ml/ml_codelab/scripts/inference/Dockerfile
imaging/ml/ml_codelab/scripts/inference/inference.py
imaging/ml/ml_codelab/scripts/inference/setup.py
imaging/ml/ml_codelab/scripts/preprocess/preprocess.py
imaging/ml/ml_codelab/scripts/tcia_utils.py
imaging/ml/ml_codelab/scripts/trainer/model.py
imaging/ml/ml_codelab/setup.py

this PR contains:
-   switch from Python2 to Python3. without ipynb files and readme update
-   venev has been removed from dockerbuild of inference due it's useless in docker image

[none] switch from Python2 to Python3

---

imaging/ml/ml_codelab/breast_density_auto_ml.ipynb
imaging/ml/ml_codelab/breast_density_cloud_ml.ipynb

@codezizo
this PR contains:
- spacing update of ipynb files, made by saving files by yupyter without any changes

[none] update of spacing in ipynb files

---

fhir/immunizations_demo/scripts/assemble_training_data.py
fhir/lung-cancer/scripts/assemble_training_data.py

Explicitly replace "import tensorflow" with "tensorflow.compat.v1"

Explicitly replace "import tensorflow" with "tensorflow.compat.v1"

---

deploy/config/terraform.go

enable spanner api by default if instances set

enable spanner api by default if instances set

---

deploy/apply/terraform.go
deploy/cmd/apply/testdata/commands.txt
deploy/config/tfconfig/project.go

use gcloud to link billing account

use gcloud to link billing account

---

imaging/ml/ml_codelab/breast_density_auto_ml.ipynb

this PR contains first step of revert - update of breast_density_auto_ml.ipynb

revert of #423

---

deploy/apply/terraform_test.go
deploy/cmd/apply/testdata/commands.txt
deploy/config/tfconfig/bigquery.go

update bigquery dataset import format to one that works for both provider version 2 and 3

update bigquery dataset import format to one that works for both provider version 2 and 3

---

imaging/ml/ml_codelab/README.md
imaging/ml/ml_codelab/breast_density_auto_ml.ipynb
imaging/ml/ml_codelab/breast_density_cloud_ml.ipynb
imaging/ml/ml_codelab/scripts/inference/inference.py
imaging/ml/ml_codelab/scripts/preprocess/preprocess.py
imaging/ml/ml_codelab/setup.py

update of codelab to python3

---

deploy/config/tfconfig/bigquery.go

Add support for domain under bigquery dataset.

Add support for domain under bigquery dataset.

---

deploy/policygen/BUILD
deploy/policygen/README.md
deploy/policygen/main.go
deploy/policygen/tfplan/BUILD
deploy/policygen/tfplan/testdata/BUILD
deploy/policygen/tfplan/testdata/test.plan.json
deploy/policygen/tfplan/tfplan.go
deploy/policygen/tfplan/tfplan_test.go

Add initial code for new policy generator.
- Add main binary.
- Add logic to read TF plan.json to go struct.

Add initial code for new policy generator.

---

fhir/immunizations_demo/docs/README.md

Fix typo in FHIR Immunizations Demo README.md

Fix typo in FHIR Immunizations Demo README.md

---

fhir/immunizations_demo/frontend/tslint.json

Use respectful terminology

---

fhir/immunizations_demo/frontend/src/app/_app-theme.scss
fhir/immunizations_demo/frontend/src/app/immunizations/immunization-form/_immunization-form-theme.scss
fhir/immunizations_demo/frontend/src/app/patient-panel/_patient-panel-theme.scss
fhir/immunizations_demo/frontend/src/styles.scss

Update to new Angular Material theming API based on `@use`

Update to new Angular Material theming API based on `@use`

---

utilities/README.md

Fixes https://github.com/GoogleCloudPlatform/healthcare/issues/573
Rendering snippet below.

Healthcare Toolkit ReadMe
