deploy/cft/cft.go, deploy/cft/cft_test.go, deploy/project_config.yaml.schema, deploy/rulegen/bigquery_test.go, deploy/rulegen/location_test.go, deploy/rulegen/resource_test.go
rename bigquery_dataset to bq_dataset for consistency with other resource names.
=> rename bigquery_dataset to bq_dataset for consistency with other resource names.

deploy/apply/apply.go
only retry once for concurrent iam failures
=> only retry once for concurrent iam failures

deploy/apply/gke.go, deploy/apply/gke_test.go
Do not add "-cluster" after the GKE clusters' names any more.
=> Do not add "-cluster" after the GKE clusters' names any more.

deploy/utils/utils.py
Use safe_substitute instead of substitute to replace environment variables.
=> Use safe_substitute instead of substitute to replace environment variables.

deploy/apply/apply.go, deploy/apply/forseti.go, deploy/apply/options.go, deploy/cmd/apply/apply.go
Loose condition to run rule generation as long as forseti config exists.
=> Loose condition to run rule generation as long as forseti config exists.

deploy/config/load.go, deploy/config/load_test.go, deploy/project_config.yaml.schema
move generated_fields_path higher up in the config schema, minor wording change, don't make intermediate dirs
=> move generated_fields_path higher up in the config schema, minor wording change, don't make intermediate dirs

deploy/apply/forseti.go, deploy/apply/terraform.go, deploy/config/config.go, deploy/project_config.yaml.schema, deploy/samples/project_with_local_audit_logs.yaml, deploy/samples/project_with_remote_audit_logs.yaml, deploy/samples/spanned_configs/projects/partial_audit.yaml, deploy/samples/terraform.yaml, deploy/testconf/testconf.go
rename terraform block in project to devops for consistency with top level devops config
=> rename terraform block in project to devops for consistency with top level devops config

deploy/apply/terraform.go, deploy/apply/terraform_test.go, deploy/config/config.go, deploy/project_config.yaml.schema, deploy/terraform/BUILD, deploy/terraform/apply.go, deploy/terraform/apply_test.go
make custom teraform configs more flexible
The following changes are made:
- resources_deployment is renamed to terraform_deployments
- Allow multiple deployments to be referenced (initially only resources supported)
- Within a deployment, allow multiple fields to be configured (currently only 'config' can be configured).
- Merge the config with the final config, and not parse into our intermediate form. This allows the user to use the official terraform JSON config style and also set any field without needing to understand our middle layer or wait for support from us.
=> make custom teraform configs more flexible

deploy/config/load_test.go, deploy/project_config.yaml.schema
stop requiring projects to be set
=> stop requiring projects to be set

deploy/cmd/apply/testdata/project_with_remote_audit_logs_dryrun_commands.txt, deploy/runner/runner.go, deploy/terraform/apply.go
Always copy Terraform modules to running dir, even in dryrun.
=> Always copy Terraform modules to running dir, even in dryrun.

deploy/README.md
more fixes for documentation:
- remove deprecated flag documentation
- don't reference deployment manager samples
- remove go pre requisite as it will be setup by bazel
- don't mention deployment manager in intro
=> more fixes for documentation:

deploy/README.md
clarify the cd directory will be used to run bazel commands
=> clarify the cd directory will be used to run bazel commands

deploy/apply/terraform.go, deploy/apply/terraform_test.go
rename data project ID resource to 'project' for consistency
=> rename data project ID resource to 'project' for consistency

deploy/starlark/config_test.bzl
Extends config_test rule to further verify (beyond loading the config) GCP yaml files.
This test runs the apply command (with --dry_run) and can be used to verify the generated terraform configs in different ways:
1) on test logs
2) on the $TEST_UNDECLARED_OUTPUTS_DIR/PROJECT_ID/{audit, project, resources, services, state}/main.tf.json
=> Extends config_test rule to further verify (beyond loading the config) GCP yaml files.

deploy/samples/deployment_manager/BUILD, deploy/samples/environments/BUILD, deploy/samples/full/BUILD, deploy/starlark/config_test.bzl
Refactor test dependencies to make dependency on terraform_google_forseti explicit.
=> Refactor test dependencies to make dependency on terraform_google_forseti explicit.

imaging/ml/ml_codelab/README.md, imaging/ml/ml_codelab/breast_density_auto_ml.ipynb, imaging/ml/ml_codelab/breast_density_cloud_ml.ipynb, imaging/ml/ml_codelab/scripts/preprocess/preprocess.py
based on https://github.com/GoogleCloudPlatform/healthcare/pull/423
- switch from gcs storage to hcapi hosted data - **done**
- remove redundant TCIA api code - **done**
- `gcloud beta healthcare dicom-stores export` instead of api call - **done**
- should be exported only train images that label breast density 2 or 3, avoid filter blacklisted dicoms - actually filtering already performed by https://github.com/GoogleCloudPlatform/healthcare/blob/master/imaging/ml/ml_codelab/scripts/tcia_utils.py#L77 and https://github.com/GoogleCloudPlatform/healthcare/blob/master/imaging/ml/ml_codelab/scripts/tcia_utils.py#L81
not yet resolved: access to https://healthcare.googleapis.com/v1beta1/projects/chc-tcia/locations/us-central1/datasets/cbis-ddsm/dicomStores/cbis-ddsm seems to be managed by …
=> [#433] switch from gcs storage to hcapi hosted data

deploy/README.md
clarify cloud shell as officially supported env
=> clarify cloud shell as officially supported env

fhir/immunizations_demo/docs/README.md, fhir/immunizations_demo/inference/main.py
This cloud function was returning "resource not found" errors when trying to retrieve ../resources/Patient/... using v1beta1. Documentation references .../fhir/Patient/... as the location of the Patient record needed. Updating this path constructor eliminates the error and produces the expected results as observed in the function logs and the FHIR Immunizations web app.
=> Update path constructor for fhir resources

deploy/starlark/config_test.bzl
Remove dependency on TEST_FAILURE_UNDECLARED_OUTPUTS_DIR as it now contains subdirs and we need a clean directory to run the tests.
=> Remove dependency on TEST_FAILURE_UNDECLARED_OUTPUTS_DIR as it now contains subdirs and we need a clean directory to run the tests.

fhir/immunizations_demo/models/trainer/model.py, fhir/lung-cancer/models/trainer/model.py
Explicitly replace "import tensorflow" with "tensorflow.compat.v1" for TF2.x migration
=> Explicitly replace "import tensorflow" with "tensorflow.compat.v1" for TF2.x migration

CONTRIBUTING.md
Fixes https://github.com/GoogleCloudPlatform/healthcare/issues/544 by adding to `Contributing.MD`.
Rendered view of table:
=> Adding to Contributing.MD
